Repository darwinia-network/darwinia, pull requests merged in 2020-01, with the labels that each got.

#212 tests for staking module
  srml/staking/src/lib.rs
  srml/staking/src/mock.rs
  srml/staking/src/tests.rs
Labels: A0-pleasereview

#231 trival: rustfmt
  srml/staking/src/mock.rs
  srml/staking/src/tests.rs
Labels: Q0-trivial

#233 Add pre-commit git hook & bootstrap script
  .hooks/pre-commit
  .travis.yml
  README.adoc
  ci/script.sh
  scripts/bootstrap.sh
Labels: A0-pleasereview, Q0-trivial

#236 README
  README.adoc
Labels: A0-pleasereview, Q0-trivial

#239 Fix documentation
  Cargo.toml
  README.adoc
  node/cli/bin/main.rs
  node/cli/src/lib.rs
Labels: A0-pleasereview, Q0-trivial

#237 Trival/bootstrap
  README.adoc
  scripts/bootstrap.sh
Labels: A0-pleasereview, Q0-trivial

#243 Icefrog
  .hooks/pre-commit
  .travis.yml
  Cargo.lock
  Cargo.toml
  README.adoc
  ci/script.sh
  node/cli/Cargo.toml
  node/cli/bin/main.rs
  node/cli/src/lib.rs
  node/runtime/src/lib.rs
  scripts/bootstrap.sh
  srml/staking/src/lib.rs
  srml/staking/src/mock.rs
  srml/staking/src/tests.rs
Labels: A0-pleasereview

#241 Preset the keys of Alice & Bob
  node/cli/res/icefrog.json
  node/cli/src/chain_spec.rs
  node/cli/src/lib.rs
Labels: A0-pleasereview

#248 update: constant
  srml/timestamp/src/lib.rs
Labels: A0-pleasereview
