Repository darwinia-network/darwinia, pull requests merged in 2020-03, with the labels that each got.

#308 Update LICENSE
  LICENSE
  README.adoc
Labels: A0-pleasereview, A2-insubstantial

#311 keep balances instead of ring as default balance mod name
  bin/node/cli/src/chain_spec.rs
  bin/node/cli/src/factory_impl.rs
  bin/node/runtime/src/lib.rs
Labels: A0-pleasereview

#306 Treasury support KTON Proposal
  .maintain/ci/travis.local.sh
  .travis.yml
  bin/node/runtime/src/lib.rs
  frame/balances/README.adoc
  frame/balances/kton/README.adoc
  frame/balances/kton/src/lib.rs
  frame/balances/ring/README.adoc
  frame/balances/ring/src/lib.rs
  frame/treasury/README.adoc
  frame/treasury/src/lib.rs
  frame/treasury/src/tests.rs
Labels: A0-pleasereview

#307 Refactoring Balances
  Cargo.lock
  frame/balances/kton/Cargo.toml
  frame/balances/kton/src/lib.rs
  frame/balances/kton/src/mock.rs
  frame/balances/kton/src/tests.rs
  frame/balances/ring/Cargo.toml
  frame/balances/ring/src/lib.rs
  frame/balances/ring/src/mock.rs
  frame/balances/ring/src/tests.rs
  frame/support/Cargo.toml
  frame/support/src/lib.rs
  frame/support/src/structs.rs
  frame/support/src/traits.rs
Labels: A0-pleasereview, B2-breaksapi, bug

#324 Code Clean
  .maintain/types/types.json
  .maintain/types/types.toml
  Cargo.lock
  bin/node/cli/res/crab.json
  bin/node/cli/src/chain_spec.rs
  bin/node/cli/src/lib.rs
  bin/node/runtime/src/constants.rs
  bin/node/runtime/src/lib.rs
  frame/staking/Cargo.toml
  frame/vesting/Cargo.toml
Labels: A3-inprogress

#328 fix: genesis for ring and kton
  frame/balances/kton/src/lib.rs
  frame/balances/ring/src/lib.rs
Labels: A0-pleasereview

#326 Fix treasury's tests for v2.0.0-alpha.3
  frame/treasury/src/tests.rs
Labels: A0-pleasereview

#329 Fixing eth relay and backing tests
  .maintain/ci/travis.local.sh
  .travis.yml
  Cargo.lock
  bin/node/executor/tests/submit_transaction.rs
  frame/chainrelay/eth/backing/Cargo.toml
  frame/chainrelay/eth/backing/src/mock.rs
  frame/chainrelay/eth/backing/src/tests.rs
  frame/chainrelay/eth/relay/src/lib.rs
  frame/chainrelay/eth/relay/src/tests.rs
  frame/vesting/src/lib.rs
Labels: A0-pleasereview

#332 Update readme with Riot room
  README.adoc
Labels: A0-pleasereview

#331 Fix tests of Staking for Crab
  frame/staking/CHANGELOG.md
  frame/staking/src/darwinia_tests.rs
  frame/staking/src/lib.rs
  frame/staking/src/mock.rs
  frame/staking/src/substrate_tests.rs
  frame/staking/src/tests.rs
Labels: A0-pleasereview

#342 Add benchmark for balances
  Cargo.lock
  bin/node/cli/Cargo.toml
  bin/node/cli/src/cli.rs
  bin/node/cli/src/command.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  client/cli/Cargo.toml
  client/cli/src/error.rs
  frame/balances/README.adoc
  frame/balances/ring/Cargo.toml
  frame/balances/ring/src/benchmarking.rs
  frame/balances/ring/src/lib.rs
Labels: A0-pleasereview

#350 Review Eth-Backing, Support
  frame/chainrelay/eth/backing/src/lib.rs
  frame/chainrelay/eth/backing/src/tests.rs
  frame/chainrelay/eth/relay/src/lib.rs
  frame/support/src/structs.rs
Labels: A0-pleasereview

#354 Review all weights
  frame/balances/README.adoc
  frame/chainrelay/eth/backing/README.md
  frame/chainrelay/eth/backing/src/lib.rs
  frame/chainrelay/eth/relay/README.md
  frame/chainrelay/eth/relay/src/lib.rs
  frame/elections-phragmen/README.md
  frame/staking/CHANGELOG.md
  frame/staking/README.md
  frame/staking/src/lib.rs
  frame/treasury/README.adoc
Labels: A0-pleasereview

#359 Merge Dot into Eth
  .maintain/types/types.json
  .maintain/types/types.toml
  frame/claims/src/lib.rs
  primitives/merkle-patricia-trie/benches/trie.rs
Labels: A0-pleasereview

#335 Add ethereum offchain worker
  .travis.yml
  Cargo.lock
  Cargo.toml
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/chainrelay/eth/offchain/Cargo.toml
  frame/chainrelay/eth/offchain/src/lib.rs
  frame/chainrelay/eth/offchain/src/mock.rs
  frame/chainrelay/eth/offchain/src/tests.rs
  primitives/eth-primitives/Cargo.toml
Labels: A0-pleasereview

#386 Fix Tron claim and signable message
  frame/claims/src/lib.rs
Labels: A0-pleasereview

#387 Fix ci test case flow
  .travis.yml
Labels: A0-pleasereview

#393 Clean Offchain Builds
  .maintain/clean-offchain-builds.py
Labels: A0-pleasereview

#394 remove: offchain debug builds and WASM targets
  .maintain/clean-offchain-builds.py
Labels: A0-pleasereview

#361 Add tests for check_receipt in eth-relay
  .gitignore
  Cargo.lock
  frame/chainrelay/eth/relay/Cargo.toml
  frame/chainrelay/eth/relay/src/lib.rs
  frame/chainrelay/eth/relay/src/mock.rs
  frame/chainrelay/eth/relay/src/mock_headers/check_receipt.rs
  frame/chainrelay/eth/relay/src/mock_headers/mod.rs
  frame/chainrelay/eth/relay/src/mock_headers/utils.rs
  frame/chainrelay/eth/relay/src/tests.rs
Labels: A0-pleasereview, A3-inprogress

#404 Fix merge ring and kton
  .maintain/types/types.json
  Cargo.lock
  README.adoc
  bin/node/cli/Cargo.toml
  bin/node/cli/src/chain_spec.rs
  bin/node/cli/src/factory_impl.rs
  bin/node/runtime/Cargo.toml
  bin/node/runtime/README.adoc
  bin/node/runtime/src/impls.rs
  bin/node/runtime/src/lib.rs
  bin/node/testing/Cargo.toml
Labels: A0-pleasereview

#406 ci: free the nightly version of Rust
  .travis.yml
Labels: A0-pleasereview
