Repository darwinia-network/darwinia, pull requests merged in 2020-09, with the labels that each got.

#515 Release 0.6.9
  Cargo.lock
  Cargo.toml
  README.adoc
  cli/Cargo.toml
  node/service/Cargo.toml
  node/service/src/chain_spec.rs
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/crab/Cargo.toml
  runtime/crab/src/lib.rs
Labels: A0-pleasereview

#518 Fix Guard
  runtime/crab/src/lib.rs
Labels: A0-pleasereview

#520 Migrate Module Id
  primitives/src/lib.rs
  runtime/crab/src/lib.rs
Labels: A0-pleasereview

#522 Companion for #274
  Cargo.lock
  node/service/src/chain_spec.rs
  primitives/src/lib.rs
  runtime/crab/Cargo.toml
  runtime/crab/src/lib.rs
Labels: A0-pleasereview

#523 Release 0.6.10
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  node/service/Cargo.toml
  node/service/src/chain_spec.rs
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/crab/Cargo.toml
  runtime/crab/darwinia_types.json
  runtime/crab/polkadot_compatible_types.json
  runtime/crab/src/lib.rs
Labels: A0-pleasereview

#526 Proxy `EthereumBridge`
  runtime/crab/darwinia_types.json
  runtime/crab/polkadot_compatible_types.json
  runtime/crab/src/lib.rs
Labels: A0-pleasereview

#529 Release 0.6.11
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  node/service/Cargo.toml
  node/service/src/chain_spec.rs
  primitives/Cargo.toml
  primitives/src/lib.rs
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/crab/Cargo.toml
  runtime/crab/darwinia_types.json
  runtime/crab/polkadot_compatible_types.json
  runtime/crab/src/lib.rs
Labels: A0-pleasereview, D1-runtime-migration, D2-remove-migration, E1-new-types

#546 Companion for #300
  Cargo.lock
Labels: A0-pleasereview

#543 Fix Vesting And Genesis Ring
  .maintain/utility/crab-genesis-swap.json
  .maintain/utility/ethereum-tron-genesis-swap-kton.json
  .maintain/utility/ethereum-tron-genesis-swap-ring.json
  .maintain/utility/format-genesis-swap.py
  node/service/res/crab-genesis-swap.json
  node/service/res/ethereum-genesis-swap-kton.json
  node/service/res/ethereum-genesis-swap-ring.json
  node/service/res/ethereum-tron-genesis-swap-kton.json
  node/service/res/ethereum-tron-genesis-swap-ring.json
  node/service/res/tron-genesis-swap-kton.json
  node/service/res/tron-genesis-swap-ring.json
  node/service/src/chain_spec.rs
  runtime/darwinia/src/constants.rs
  runtime/darwinia/src/lib.rs
Labels: A0-pleasereview

#545 Add Democracy
  Cargo.lock
  node/service/src/chain_spec.rs
  runtime/crab/Cargo.toml
  runtime/crab/polkadot-compatible-types.json
  runtime/crab/src/lib.rs
  runtime/crab/src/weights/darwinia_democracy.rs
  runtime/crab/src/weights/mod.rs
  runtime/crab/types.json
Labels: A0-pleasereview, E1-new-types

#555 Release 0.7.0-beta.2
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  node/service/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/crab/Cargo.toml
  runtime/crab/src/lib.rs
  runtime/darwinia/Cargo.toml
Labels: D1-runtime-migration
