Repository darwinia-network/darwinia, pull requests merged in 2021-04, with the labels that each got.

#632 Use `sr-tool` for Release
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .maintain/README.md
  .maintain/README_zh_CN.md
  .maintain/complete-build.sh
  .maintain/docker/Dockerfile.aarch64-linux-gnu
  .maintain/docker/Dockerfile.darwinia.x86_64-linux-gnu
  .maintain/docker/Dockerfile.mirror-chn.aarch64-linux-gnu
  .maintain/docker/Dockerfile.mirror-chn.x86_64-linux-gnu
  .maintain/docker/Dockerfile.x86_64-linux-gnu
  .maintain/setup-darwinia.sh
  .maintain/setup-image.sh
  .maintain/setup-wasm.sh
  .maintain/utility/release
  CHANGELOG.md
Labels: CI/CD

#642 Tag v0.9.6
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  node/service/Cargo.toml
  primitives/Cargo.toml
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/crab/Cargo.toml
  runtime/darwinia/Cargo.toml
Labels: Release

#646 Seperate Service
  Cargo.lock
  cli/Cargo.toml
  cli/src/browser.rs
  cli/src/command.rs
  cli/src/lib.rs
  node/service/src/client.rs
  node/service/src/lib.rs
  node/service/src/service/crab.rs
  node/service/src/service/darwinia.rs
  node/service/src/service/mod.rs
  rpc/src/crab.rs
  rpc/src/darwinia.rs
  rpc/src/lib.rs
  runtime/crab/src/lib.rs
Labels: P8 High

#643 Add dvm to crab
  Cargo.lock
  node/service/Cargo.toml
  node/service/src/chain_spec/crab.rs
  node/service/src/service/crab.rs
  node/service/src/service/darwinia.rs
  node/service/src/service/mod.rs
  rpc/Cargo.toml
  rpc/src/crab.rs
  runtime/crab/Cargo.toml
  runtime/crab/src/lib.rs
  runtime/crab/src/pallets/dvm.rs
  runtime/crab/src/pallets/evm.rs
  runtime/crab/src/pallets/mod.rs
Labels: P7 High

#649 remove cache, fix ci no space left error
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: CI/CD

#650 Update `cross`
  .maintain/setup-darwinia.sh
  .maintain/utility/release
Labels: CI/CD

#654 support on-chain-release-build feature
  .maintain/setup-wasm.sh
Labels: CI/CD

#657 Tag v0.10.0
  CHANGELOG.md
Labels: Release
