Repository darwinia-network/darwinia, pull requests merged in 2023-12, with the labels that each got.

#1342 Enable EIP-1559
  .maintain/pallet-weight-template.hbs
  Cargo.lock
  pallet/account-migration/src/weights.rs
  pallet/deposit/Cargo.toml
  pallet/deposit/src/weights.rs
  pallet/ecdsa-authority/src/weights.rs
  pallet/staking/src/weights.rs
  runtime/common/Cargo.toml
  runtime/common/src/lib.rs
  runtime/common/src/test.rs
  runtime/crab/src/pallets/evm.rs
  runtime/darwinia/src/pallets/evm.rs
  runtime/darwinia/src/pallets/orml_xtokens.rs
  runtime/pangolin/src/pallets/evm.rs
  runtime/pangolin/src/pallets/orml_xtokens.rs
  runtime/pangolin/src/pallets/tx_pause.rs
  runtime/pangoro/src/pallets/evm.rs
  tool/weight-checker/src/t.rs
Labels: S-Need Audit, C-Runtime

#1345 Restructure
  runtime/crab/src/pallets/democracy.rs
  runtime/crab/src/pallets/governance.rs
  runtime/crab/src/pallets/governance/treasury.rs
  runtime/crab/src/pallets/treasury.rs
  runtime/pangolin/src/pallets/governance.rs
  runtime/pangolin/src/pallets/governance/treasury.rs
Labels: U-Housekeeping

#1346 Collection of pallet constants
  pallet/message-transact/src/mock.rs
  runtime/common/src/lib.rs
  runtime/common/src/pallet_config.rs
  runtime/crab/src/pallets/assets.rs
  runtime/crab/src/pallets/balances.rs
  runtime/crab/src/pallets/fee_market.rs
  runtime/crab/src/pallets/governance.rs
  runtime/darwinia/src/pallets/assets.rs
  runtime/darwinia/src/pallets/balances.rs
  runtime/darwinia/src/pallets/fee_market.rs
  runtime/darwinia/src/pallets/treasury.rs
  runtime/pangolin/src/pallets/assets.rs
  runtime/pangolin/src/pallets/balances.rs
  runtime/pangolin/src/pallets/fee_market.rs
  runtime/pangolin/src/pallets/governance.rs
  runtime/pangoro/src/pallets/assets.rs
  runtime/pangoro/src/pallets/balances.rs
  runtime/pangoro/src/pallets/fee_market.rs
  runtime/pangoro/src/pallets/treasury.rs
Labels: U-Housekeeping

#1347 Upgrade to the frontier patch version
  Cargo.lock
Labels: D-Frontier

#1350 Release `pango-6511`
  runtime/pangolin/src/lib.rs
  runtime/pangoro/src/lib.rs
Labels: U-Release, N-Pangoro, N-Pangolin

#1351 Update artifacts action
  .github/workflows/release.yml
Labels: U-CI/CD

#1352 Bump action
  .github/workflows/checks.yml
Labels: U-CI/CD

#1355 Simplify release action
  .github/workflows/release.yml
Labels: U-CI/CD

#1356 Fix CI
  .github/workflows/release.yml
Labels: U-CI/CD

#1357 Fix CI
  .github/workflows/release.yml
Labels: U-CI/CD

#1358 Improve actions
  .github/actions/build/action.yml
  .github/workflows/checks.yml
  .github/workflows/release.yml
  .github/workflows/staging.yml
Labels: U-CI/CD

#1359 Add skip build
  .github/actions/build/action.yml
  .github/workflows/release.yml
  .github/workflows/staging.yml
Labels: U-CI/CD

#1360 Remove spaces
  .github/actions/build/action.yml
  .github/workflows/release.yml
Labels: U-CI/CD

#1361 Enable production
  .github/actions/build/action.yml
  .github/note-template/node.md
  .github/note-template/runtime.md
  .github/workflows/release.yml
Labels: U-CI/CD

#1362 Fetch Dockerfile
  .github/workflows/release.yml
  .github/workflows/staging.yml
Labels: U-CI/CD

#1363 Improve CI
  .github/workflows/release.yml
Labels: U-CI/CD

#1364 Fix CI
  .github/workflows/release.yml
Labels: U-CI/CD

#1365 Fix CI
  .github/actions/build/action.yml
  .github/workflows/release.yml
Labels: U-CI/CD

#1366 Fix quote
  .github/workflows/release.yml
Labels: U-CI/CD

#1367 Export `CHAIN`
  .github/workflows/release.yml
Labels: U-CI/CD

#1369 Fetch template
  .github/workflows/release.yml
Labels: U-CI/CD

#1370 Release `v6.5.1-1`
  Cargo.lock
  Cargo.toml
  runtime/crab/src/lib.rs
  runtime/crab/src/migration.rs
  runtime/darwinia/src/lib.rs
Labels: N-Crab, N-Darwinia, U-Release, S-Patch
