Repository darwinia-network/darwinia, pull requests merged in 2024-03, with the labels that each got.

#1425 Update staking precompile method
  precompile/metadata/abi/staking.json
  precompile/metadata/sol/staking.sol
  precompile/staking/src/lib.rs
  precompile/staking/src/mock.rs
  precompile/staking/src/tests.rs
Labels: Bk-API

#1428 Rename the runtime-transact
  Cargo.lock
  Cargo.toml
  pallet/ethtx-forwarder/Cargo.toml
  pallet/ethtx-forwarder/src/lib.rs
  pallet/ethtx-forwarder/src/mock.rs
  pallet/ethtx-forwarder/src/tests/eip1559.rs
  pallet/ethtx-forwarder/src/tests/eip2930.rs
  pallet/ethtx-forwarder/src/tests/legacy.rs
  pallet/ethtx-forwarder/src/tests/mod.rs
  pallet/staking/Cargo.toml
  pallet/staking/src/lib.rs
  runtime/crab/Cargo.toml
  runtime/crab/src/lib.rs
  runtime/crab/src/pallets.rs
  runtime/crab/src/pallets/ethtx_forwarder.rs
  runtime/crab/src/pallets/evm.rs
  runtime/crab/src/pallets/tx_pause.rs
  runtime/darwinia/Cargo.toml
  runtime/darwinia/src/lib.rs
  runtime/darwinia/src/pallets.rs
  runtime/darwinia/src/pallets/ethtx_forwarder.rs
  runtime/darwinia/src/pallets/evm.rs
  runtime/darwinia/src/pallets/tx_pause.rs
  runtime/pangolin/Cargo.toml
  runtime/pangolin/src/lib.rs
  runtime/pangolin/src/pallets.rs
  runtime/pangolin/src/pallets/ethtx_forwarder.rs
  runtime/pangolin/src/pallets/evm.rs
  runtime/pangolin/src/pallets/tx_pause.rs
Labels: U-Housekeeping

#1419 Add spender tracks
  runtime/common/src/pallet_config.rs
  runtime/crab/src/pallets/governance.rs
  runtime/crab/src/pallets/governance/origin.rs
  runtime/crab/src/pallets/governance/track.rs
  runtime/darwinia/src/pallets/governance.rs
  runtime/darwinia/src/pallets/governance/origin.rs
  runtime/darwinia/src/pallets/governance/track.rs
  runtime/pangolin/src/pallets/governance.rs
  runtime/pangolin/src/pallets/governance/origin.rs
  runtime/pangolin/src/pallets/governance/track.rs
Labels: S-Need Audit, C-Runtime

#1431 Add migration
  runtime/common/src/lib.rs
  runtime/common/src/migration_helper.rs
  runtime/crab/src/migration.rs
  runtime/darwinia/src/migration.rs
  runtime/pangolin/src/migration.rs
Labels: S-Need Audit

#1433 Release `pango-6602`
  .github/workflows/checks.yml
  .github/workflows/release.yml
  Cargo.lock
  Cargo.toml
  pallet/staking/src/lib.rs
  precompile/bls12-381/src/lib.rs
  runtime/common/src/xcm_configs.rs
  runtime/crab/src/pallets/proxy.rs
  runtime/darwinia/src/pallets/proxy.rs
  runtime/pangolin/src/lib.rs
  runtime/pangolin/src/pallets/proxy.rs
  rust-toolchain.toml
Labels: U-Prerelease

#1436 Add --features=on-chain-release-build
  .github/workflows/release.yml
Labels: U-CI/CD

#1437 Update runtime override params
  .github/workflows/runtime-override.yml
Labels: U-CI/CD

#1448 Update Proposal Hash to Whitelist Hash
  .github/note-template/runtime.md
  .github/workflows/release.yml
Labels: U-CI/CD

#1449 Fix release notifier
  .github/workflows/notify-release.yml
Labels: U-CI/CD

#1453 Use `deposit_creating`
  pallet/staking/src/mock.rs
  runtime/darwinia/src/migration.rs
  runtime/darwinia/src/pallets/staking.rs
Labels: B-Runtime

#1459 Use `gh`
  .github/workflows/notify-release.yml
  .github/workflows/release.yml
Labels: U-CI/CD
