Repository darwinia-network/darwinia, pull requests merged in 2024-04, with the labels that each got.

#1463 Half the gas price
  runtime/common/src/lib.rs
  runtime/common/src/test.rs
Labels: C-Runtime

#1467 Release `pango-6611`
  runtime/crab/src/migration.rs
  runtime/darwinia/src/migration.rs
  runtime/pangolin/src/lib.rs
  runtime/pangolin/src/migration.rs
Labels: U-Prerelease

#1408 KTON staking
  Cargo.lock
  pallet/account-migration/src/benchmarking.rs
  pallet/account-migration/src/lib.rs
  pallet/account-migration/src/mock.rs
  pallet/staking/Cargo.toml
  pallet/staking/src/benchmarking.rs
  pallet/staking/src/lib.rs
  pallet/staking/src/migration.rs
  pallet/staking/src/migration/v1.rs
  pallet/staking/src/migration/v2.rs
  pallet/staking/src/mock.rs
  pallet/staking/src/tests.rs
  precompile/metadata/abi/staking.json
  precompile/metadata/sol/staking.sol
  precompile/staking/src/lib.rs
  precompile/staking/src/mock.rs
  precompile/staking/src/tests.rs
  runtime/common/src/test.rs
  runtime/crab/src/lib.rs
  runtime/crab/src/pallets/staking.rs
  runtime/darwinia/src/lib.rs
  runtime/darwinia/src/pallets/staking.rs
  runtime/pangolin/src/lib.rs
  runtime/pangolin/src/migration.rs
  runtime/pangolin/src/pallets/staking.rs
Labels: Bk-Storage, S-Need Audit, C-Pallet

#1475 Implement DIP-6
  node/src/chain_spec/crab.rs
  node/src/chain_spec/darwinia.rs
  node/src/chain_spec/pangolin.rs
  pallet/account-migration/src/benchmarking.rs
  pallet/account-migration/src/lib.rs
  pallet/account-migration/src/mock.rs
  pallet/staking/src/benchmarking.rs
  pallet/staking/src/lib.rs
  pallet/staking/src/migration/v2.rs
  pallet/staking/src/mock.rs
  pallet/staking/src/tests.rs
  pallet/staking/src/weights.rs
  pallet/staking/traits/src/lib.rs
  precompile/staking/src/lib.rs
  precompile/staking/src/mock.rs
  precompile/staking/src/tests.rs
  runtime/common/src/test.rs
  runtime/crab/src/pallets/staking.rs
  runtime/crab/src/weights/darwinia_staking.rs
  runtime/darwinia/src/pallets/staking.rs
  runtime/darwinia/src/weights/darwinia_staking.rs
  runtime/pangolin/src/pallets/staking.rs
  runtime/pangolin/src/weights/darwinia_staking.rs
Labels: S-Audited

#1477 Fix version
  runtime/pangolin/src/lib.rs
Labels: U-Prerelease

#1480 Add some doc
  pallet/deposit/src/lib.rs
Labels: U-Housekeeping
