Repository darwinia-network/darwinia, pull requests merged in 2024-08, with the labels that each got.

#1555 Merge from `v6.6.4` release
  .github/note-template/runtime.md
  Cargo.lock
  Cargo.toml
  node/src/cli.rs
Labels: U-Release

#1554 Enable async backing
  Cargo.lock
  core/primitives/src/lib.rs
  pallet/staking/src/lib.rs
  runtime/common/Cargo.toml
  runtime/common/src/lib.rs
  runtime/common/src/pallet_config.rs
  runtime/common/src/test.rs
  runtime/crab/src/lib.rs
  runtime/crab/src/pallets/aura.rs
  runtime/crab/src/pallets/timestamp.rs
  runtime/crab/tests/tests.rs
  runtime/darwinia/src/lib.rs
  runtime/darwinia/src/pallets/aura.rs
  runtime/darwinia/src/pallets/timestamp.rs
  runtime/darwinia/tests/tests.rs
  runtime/koi/Cargo.toml
  runtime/koi/src/lib.rs
  runtime/koi/src/pallet_config.rs
  runtime/koi/src/pallets/assets.rs
  runtime/koi/src/pallets/aura.rs
  runtime/koi/src/pallets/balances.rs
  runtime/koi/src/pallets/dmp_queue.rs
  runtime/koi/src/pallets/evm.rs
  runtime/koi/src/pallets/governance.rs
  runtime/koi/src/pallets/message_queue.rs
  runtime/koi/src/pallets/parachain_system.rs
  runtime/koi/src/pallets/scheduler.rs
  runtime/koi/src/pallets/session.rs
  runtime/koi/src/pallets/system.rs
  runtime/koi/tests/tests.rs
Labels: C-Runtime

#1556 `v6.6.5` prerelease
  .github/note-template/runtime.md
  Cargo.lock
  Cargo.toml
  node/src/cli.rs
  pallet/account-migration/src/mock.rs
  pallet/staking/src/lib.rs
  pallet/staking/src/tests.rs
  runtime/crab/src/lib.rs
  runtime/crab/src/migration.rs
  runtime/darwinia/src/lib.rs
  runtime/darwinia/src/migration.rs
  runtime/koi/src/lib.rs
Labels: U-Prerelease

#1557 Update addr
  runtime/crab/src/migration.rs
  runtime/darwinia/src/migration.rs
Labels: U-Release, C-Runtime

#1559 Set storage version
  runtime/crab/src/migration.rs
  runtime/darwinia/src/migration.rs
  runtime/koi/src/migration.rs
Labels: U-Release

#1561 Update deposit precompile interfaces
  precompile/deposit/src/lib.rs
  precompile/deposit/src/tests.rs
  precompile/metadata/abi/deposit.json
  precompile/metadata/sol/deposit.sol
Labels: C-Precompile

#1563 Release `koi-6651`
  runtime/koi/src/lib.rs
Labels: U-Prerelease

#1567 Improve hybrid staking unit tests
  pallet/staking/src/lib.rs
  pallet/staking/src/mock.rs
  pallet/staking/src/tests.rs
Labels: C-Test

#1568 Remove duplicated storage item
  pallet/account-migration/Cargo.toml
  pallet/asset-limit/Cargo.toml
  pallet/deposit/Cargo.toml
  pallet/ethtx-forwarder/Cargo.toml
  pallet/staking/Cargo.toml
  pallet/staking/src/lib.rs
  pallet/staking/src/tests.rs
  pallet/staking/traits/Cargo.toml
  precompile/assets/Cargo.toml
  precompile/deposit/Cargo.toml
  precompile/staking/Cargo.toml
  precompile/state-storage/Cargo.toml
  runtime/common/Cargo.toml
  runtime/crab/Cargo.toml
  runtime/crab/src/migration.rs
  runtime/darwinia/Cargo.toml
  runtime/darwinia/src/migration.rs
  runtime/koi/Cargo.toml
  runtime/koi/src/migration.rs
Labels: C-Pallet

#1569 Release `koi-6652`
  .github/note-template/runtime.md
  runtime/koi/src/lib.rs
Labels: U-Prerelease

#1574 Release `koi-6653`
  pallet/staking/src/lib.rs
  runtime/crab/src/migration.rs
  runtime/crab/src/pallets/session.rs
  runtime/crab/src/pallets/staking.rs
  runtime/darwinia/src/migration.rs
  runtime/darwinia/src/pallets/session.rs
  runtime/darwinia/src/pallets/staking.rs
  runtime/koi/src/lib.rs
  runtime/koi/src/migration.rs
  runtime/koi/src/pallets/governance.rs
  runtime/koi/src/pallets/session.rs
Labels: U-Prerelease

#1576 Release `koi-6654`
  pallet/staking/src/lib.rs
  runtime/koi/src/lib.rs
  runtime/koi/src/migration.rs
Labels: U-Prerelease

#1578 Release `koi-6655`
  pallet/staking/src/lib.rs
  pallet/staking/src/tests.rs
  runtime/koi/src/lib.rs
Labels: U-Prerelease

#1580 DIP-7 improvement
  pallet/account-migration/src/mock.rs
  pallet/deposit/src/lib.rs
  pallet/deposit/src/mock.rs
  pallet/staking/src/benchmarking.rs
  pallet/staking/src/lib.rs
  pallet/staking/src/mock.rs
  pallet/staking/src/tests.rs
  precompile/deposit/src/mock.rs
  precompile/staking/src/mock.rs
  runtime/crab/src/pallets/deposit.rs
  runtime/crab/src/pallets/staking.rs
  runtime/darwinia/src/pallets/deposit.rs
  runtime/koi/src/pallets/deposit.rs
Labels: C-Pallet

#1581 Release `koi-6656`
  runtime/koi/src/lib.rs
Labels: U-Prerelease

#1582 Release `koi-6657`
  pallet/deposit/src/lib.rs
  runtime/koi/src/lib.rs
Labels: U-Prerelease

#1584 Handle migration failed on EVM side
  Cargo.lock
  pallet/deposit/Cargo.toml
  pallet/deposit/src/lib.rs
  pallet/ethtx-forwarder/src/lib.rs
  pallet/staking/src/lib.rs
Labels: C-EVM, C-Pallet

#1585 Migrate 10 deposits everytime
  pallet/deposit/src/lib.rs
  pallet/ethtx-forwarder/src/test.rs
Labels: C-Pallet

#1587 Release `koi-6658`
  runtime/koi/src/lib.rs
Labels: U-Prerelease
