Repository darwinia-network/darwinia, pull requests merged in 2024-06, with the labels that each got.

#1508 Add zombienet
  .gitignore
  .maintain/zombienet.toml
  README.md
  logo.png
  node/src/chain_spec/koi.rs
Labels: C-Test

#1509 Release Koi
  Cargo.lock
  node/src/chain_spec/koi.rs
  node/src/service/mod.rs
  pallet/staking/src/weights.rs
  runtime/koi/Cargo.toml
  runtime/koi/src/lib.rs
  runtime/koi/src/pallets.rs
  runtime/koi/src/pallets/account_migration.rs
  runtime/koi/src/pallets/governance.rs
  runtime/koi/src/pallets/tx_pause.rs
  runtime/koi/src/weights.rs
  runtime/koi/src/weights/cumulus_pallet_xcmp_queue.rs
  runtime/koi/src/weights/darwinia_account_migration.rs
  runtime/koi/src/weights/darwinia_deposit.rs
  runtime/koi/src/weights/darwinia_staking.rs
  runtime/koi/src/weights/frame_system.rs
  runtime/koi/src/weights/pallet_assets.rs
  runtime/koi/src/weights/pallet_balances.rs
  runtime/koi/src/weights/pallet_collective.rs
  runtime/koi/src/weights/pallet_conviction_voting.rs
  runtime/koi/src/weights/pallet_identity.rs
  runtime/koi/src/weights/pallet_preimage.rs
  runtime/koi/src/weights/pallet_proxy.rs
  runtime/koi/src/weights/pallet_referenda.rs
  runtime/koi/src/weights/pallet_scheduler.rs
  runtime/koi/src/weights/pallet_session.rs
  runtime/koi/src/weights/pallet_timestamp.rs
  runtime/koi/src/weights/pallet_treasury.rs
  runtime/koi/src/weights/pallet_tx_pause.rs
  runtime/koi/src/weights/pallet_utility.rs
  runtime/koi/src/weights/pallet_whitelist.rs
  runtime/koi/tests/tests.rs
Labels: U-Prerelease

#1510 Update CI
  .github/workflows/notify-release.yml
  .github/workflows/release.yml
Labels: U-CI/CD

#1511 Deprecate precompile
  Cargo.lock
  Cargo.toml
  precompile/bls12-381/Cargo.toml
  precompile/bls12-381/src/bls/mod.rs
  precompile/bls12-381/src/lib.rs
  runtime/crab/Cargo.toml
  runtime/crab/src/pallets/evm.rs
  runtime/darwinia/Cargo.toml
  runtime/darwinia/src/pallets/evm.rs
  runtime/koi/Cargo.toml
  runtime/koi/src/pallets/evm.rs
  tests/ethereum/test-bls.ts
  tests/tests.ts
Labels: C-Precompile
