Repository darwinia-network/darwinia, pull requests merged in 2024-07, with the labels that each got.

#1499 Support DOT
  runtime/darwinia/src/migration.rs
  runtime/darwinia/src/pallets/asset_manager.rs
  runtime/darwinia/src/pallets/evm.rs
  runtime/darwinia/src/pallets/polkadot_xcm.rs
  runtime/koi/src/migration.rs
  runtime/koi/src/pallets/asset_manager.rs
  runtime/koi/src/pallets/evm.rs
  runtime/koi/src/pallets/polkadot_xcm.rs
Labels: C-XCM

#1525 Update try-runtime stuff
  Cargo.lock
  Makefile.toml
  node/Cargo.toml
  node/src/cli.rs
  node/src/command.rs
  runtime/darwinia/src/lib.rs
Labels: C-Test

#1526 Release `koi-6331`
  runtime/common/src/migration_helper.rs
  runtime/crab/src/migration.rs
  runtime/darwinia/src/migration.rs
  runtime/koi/src/lib.rs
  runtime/koi/src/migration.rs
Labels: U-Prerelease

#1527 Revert "Bump docker/build-push-action from 5 to 6"
  .github/workflows/release.yml
  .github/workflows/staging.yml
Labels: U-CI/CD

#1529 Minor fixes
  .maintain/zombienet.toml
  runtime/crab/src/lib.rs
  runtime/koi/src/lib.rs
Labels: C-Test

#1534 Release `koi-6632`
  runtime/koi/src/lib.rs
Labels: U-Prerelease

#1539 Release `v6.6.4`
  pallet/account-migration/src/mock.rs
  runtime/crab/src/lib.rs
  runtime/darwinia/src/lib.rs
  runtime/koi/src/lib.rs
Labels: U-Release

#1541 Support evm-tracing for the ethtx-forward
  Cargo.lock
  pallet/ethtx-forwarder/Cargo.toml
  pallet/ethtx-forwarder/src/lib.rs
  runtime/crab/Cargo.toml
  runtime/darwinia/Cargo.toml
  runtime/koi/Cargo.toml
Labels: C-Test, C-EVM

#1542 Align xcm configs
  runtime/crab/src/pallets/polkadot_xcm.rs
  runtime/darwinia/src/pallets/polkadot_xcm.rs
  runtime/koi/src/pallets/polkadot_xcm.rs
Labels: C-XCM

#1548 Mutable contract address
  Cargo.lock
  pallet/account-migration/src/mock.rs
  pallet/staking/Cargo.toml
  pallet/staking/src/benchmarking.rs
  pallet/staking/src/lib.rs
  pallet/staking/src/migration.rs
  pallet/staking/src/migration/v2.rs
  pallet/staking/src/mock.rs
  pallet/staking/src/tests.rs
  pallet/staking/src/weights.rs
  precompile/staking/Cargo.toml
  precompile/staking/src/mock.rs
  precompile/staking/src/tests.rs
  runtime/crab/src/pallets/staking.rs
  runtime/crab/src/weights/darwinia_staking.rs
  runtime/darwinia/src/pallets/staking.rs
  runtime/darwinia/src/weights/darwinia_staking.rs
  runtime/koi/src/migration.rs
  runtime/koi/src/pallets/staking.rs
  runtime/koi/src/weights/darwinia_staking.rs
Labels: C-Test, C-Pallet

#1550 Release `koi-6641`
  runtime/koi/src/lib.rs
  runtime/koi/src/migration.rs
Labels: U-Prerelease

#1553 Delete ethereumxcm pallet
  Cargo.lock
  Cargo.toml
  runtime/crab/src/migration.rs
  runtime/darwinia/Cargo.toml
  runtime/darwinia/src/lib.rs
  runtime/darwinia/src/migration.rs
  runtime/darwinia/src/pallets.rs
  runtime/darwinia/src/pallets/ethereum_xcm.rs
  runtime/darwinia/src/pallets/polkadot_xcm.rs
  runtime/koi/Cargo.toml
  runtime/koi/src/lib.rs
  runtime/koi/src/migration.rs
  runtime/koi/src/pallets.rs
  runtime/koi/src/pallets/ethereum_xcm.rs
  runtime/koi/src/pallets/polkadot_xcm.rs
Labels: U-Housekeeping
